In [58]:
import numpy 

## 1. Create a null vector of size 10 but the fifth value which is 1

### Method 1

In [65]:
x=np.zeros(10,dtype=int)
x[4]=1
print(x)

[0 0 0 0 1 0 0 0 0 0]


### Method 2

In [49]:
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

## 2. Create a vector with values ranging from 10 to 49.

In [50]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3. Create a 3x3 matrix with values ranging from 0 to 8.

In [51]:
np.random.randint(low=0,high=9,size=(3,3))

array([[0, 2, 0],
       [5, 3, 6],
       [5, 1, 6]])

## 4. Find indices of non-zero elements from [1,2,0,0,4,0].

In [52]:
vec= np.array([1,2,0,0,4,0])
k=np.nonzero(vec != 0)
print(k)

(array([0, 1, 4], dtype=int64),)


## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [53]:
arr=np.random.randn(10,10)
print(arr)
min_=arr.min()
print("Minimum value : ",min_)
max_=arr.max()
print("Maximum value : ",max_)


[[-1.4329757  -0.47611927  0.35784653 -0.37196931 -1.1302149  -0.40570675
  -0.47718791  0.12518362  1.34728643 -0.41262745]
 [ 2.88057873 -0.24313153 -0.84417094  1.46893693 -0.73455542 -0.96907047
   0.52259463  0.71511325 -0.81463819  0.54946878]
 [-1.05993088  0.61549112 -1.70742131 -0.25134905 -2.69197354  1.4543354
   1.39133024 -0.27123755 -1.53701121  0.85664863]
 [ 2.05368478  0.8905343   0.24407597  0.19373415 -1.71213373  0.04692102
  -1.67543474  0.26181469  0.66405606  0.25649493]
 [-0.79349143  2.04202614 -0.28564    -0.77962569 -1.37859566  0.52295662
  -0.77410576 -0.4248941  -0.74328281 -0.61064202]
 [ 0.04997368  0.01031816 -0.30437282 -0.1390962  -1.39382119 -0.39698502
  -1.99107486  0.22389562  1.37593063  1.55426991]
 [-1.30237473  0.60868058 -1.41845072  0.39119237 -0.95246904  1.17873526
   2.35172243 -1.05038009 -1.0608264  -0.05142156]
 [-0.47872643  1.96722748  0.60105428  0.02428828 -0.14606056  0.6298758
  -0.90274878 -0.95020163  2.33063718  1.09757298]
 [

## 6. Create a random vector of size 30 and find the mean value.

In [55]:
vec=np.random.random(30)
print(np.mean(vec))


0.42728891611476894
